server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

cloud:
  aws:
    region:
      static: ap-northeast-2

spring:
  profiles:
    active: local
  config:
    import: 'aws-secretsmanager:crashMyServer/aws/be'

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: ${JWT_ACCESS_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}