name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/crashmyserver:latest

      - name: Deploy containers
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_PROD }}" > docker-compose-prod.yml
          docker-compose -f docker-compose-prod.yml down app
          docker-compose -f docker-compose-prod.yml up -d app
