name: CD Pipeline

on:
  merge_group:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for EC2
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy docker-compose-prod.yml to EC2
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_PROD }}" > docker-compose-prod.yml
          scp -o StrictHostKeyChecking=no docker-compose-prod.yml ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker-compose -f /home/ec2-user/docker-compose-prod.yml down
            docker-compose -f /home/ec2-user/docker-compose-prod.yml up -d
          EOF
