name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Make init.sql files and application config files
        run: |
          
          touch ./init.sql
          echo "${{ secrets.INIT_SQL }}" > ./init.sql 
          
          cd ./src/main/resources
          
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml

          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./application-prod.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build application
        run: ./gradlew clean build --no-daemon --exclude-task test

      - name: Build Docker image
        run: docker build --file Dockerfile -t ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPO }} .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_ID }} --password ${{ secrets.DOCKER_HUB_PW }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPO }}


