name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create docker-compose-prod.yml
        run: echo "${{ secrets.DOCKER_COMPOSE_PROD_YML }}" > docker-compose-prod.yml

      - name: Build application
        run: ./gradlew clean build --no-daemon --exclude-task test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_REPO }}:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_ID }} --password ${{ secrets.DOCKER_HUB_PW }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_REPO }}:latest

