name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # jdk 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'bellsoft'

      # gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 권한 추가
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      # 테스트를 제외한 프로젝트 빌드
      - name: Build With Gradle
        run: ./gradlew build -x test

      # 테스트를 위한 mysql 설정
      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3305
          container port: 3305
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql user: ${{ secrets.MYSQL_USER }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      # 테스트를 위한 test properties 설정
      - name: Make application-test.yml
        run: |
          cd ./src/test/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES_TEST }}" > ./application.yml
        shell: bash

      # 테스트 코드 빌드
      - name: Build With Test
        run: ./gradlew test

      # 테스트 결과 파일 생성
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
